### ISSUE TITLE
Recommended MQTT client?

### ISSUE THREAD

**Issue by hongquan** [ivmarkov/rust-esp32-std-demo#32]
Hi, which MQTT client library is recommended to use with this repo?

I tried https://crates.io/crates/rumqttc but failed to compile `ring`. Maybe this crate has not been tested with rust-esp32-std yet.

```
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/quan/Works/ESP-IDF/rust-esp32-std-demo/target/release/build/ring-d2bf2b7dc3398754/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/quan/Works/Cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Also tried, but got this:

```
error: failed to run custom build command for `openssl-sys v0.9.70`
```

**Comment by ivmarkov** [comment]
That's to be expected, because `ring` is not pure Rust and currently does not support neither the Xtensa, nor the Riscv32imc architectures used by the ESP32 chip family.

The road forward is as follows:
* Short term: provide bindings (and a set of abstract interfaces) for the ESP-IDF embedded MQTT client, as described [here](https://github.com/esp-rs/esp-idf-svc/issues/21). This would allow folks to use MQTT with TLS.
* Long term: bind ESP-IDF's mbedTLS to to some of the Rust TLS abstraction layers, as described [here](). This would allow folks to use off-the-shelf pure Rust MQTT (and HTTP) clients that do support the `rust-native-tls` abstraction. Note that MQTT clients which are hard-wired to `rusttls` will **never** be supported, because `rusttls` is hard-wired to `ring`, which - as described above - relies on native code. That is, unless `ring` implements a pure-Rust code-path in future.

In the shortest term - and only if you don't need TLS with MQTT - you can try [this crate](https://github.com/bytebeamio/rumqtt/tree/master/mqttbytes). or alternatively, you can use `unsafe` calls to call the ESP-IDF MQTT C client directly from your code.

**Comment by hongquan** [comment]
Thank you.
